### ISSUE TITLE
Feature request. Size classes

### ISSUE THREAD

**Issue by gerchicov-bp** [szk-atmosphere/MisterFusion#12]

**Comment by szk-atmosphere** [comment]
Thank you for your request!
Support `Size Class` at #16 
Please try [latest version](https://github.com/szk-atmosphere/MisterFusion/tree/0.7.0).

**Comment by szk-atmosphere** [comment]
I've fixed some bugs for Size Class.
Please use [this version](https://github.com/szk-atmosphere/MisterFusion/tree/0.8.0).
