### ISSUE TITLE
Importing without cocoapods via sources only?

### ISSUE THREAD

**Issue by gerchicov-bp** [szk-atmosphere/MisterFusion#13]
I have Obj-C code and I need to import your library but I can't use cocoapods. Could you help me with it?

**Comment by szk-atmosphere** [comment]
Thank you for your question.
You can use MisterFusion in objective-c to write `#import "#Your-ProjectName#-Swift.h"`.
#Your-ProjectName#-Swift.h is automatically generated when you import swift sources in objective-c project.

**Comment by gerchicov-bp** [comment]
There is something wrong with this way - many errors appear with ```Array+MisterFusion.swift```:
Use of undeclared type 'NSLayoutConstraint'
Use of undeclared type 'UIView'
Use of undeclared type 'NSLayoutAttribute'
and etc.

I just created an empty project, created an empty swift file (to force creating of bridged header file) and added 2 swift files from this library.

**Comment by szk-atmosphere** [comment]
I've fixed that issue! 
[Array+MisterFusion.swif](https://github.com/szk-atmosphere/MisterFusion/blob/master/MisterFusion/Array%2BMisterFusion.swift)
Please pull latest version from master repository.

**Comment by gerchicov-bp** [comment]
thanks
